### PR TITLE
Adjust to use vimL based plugin starting mechanism

### PR DESCRIPTION
**Pull request by saep**
The general idea originally came from @tek .

Since it can be difficult/impossible with the current design to install plugins next to each other if they need different versions of the the same dependency, starting multiple nvim-hs instances seems like a good way to get around this.

Together with the scripts from the new repository [nvim-hs.vim](https://github.com/neovimhaskell/nvim-hs.vim), multiple nvim-hs instance can be started next to each other. With a little bit of simple boilerplate, nvim-hs plugins can also be shipped like regular neovim plugins. 

To use my ghcid plugin with vim-plugged, you will simply need the following in your neovim config:
```vim
Plug '~/src/nvim-hs.vim'
Plug 'saep/nvim-hs-ghcid', { 'for': ['haskell'], }
```

You can still use a personal Haskell project to combine plugins. However, since the scripts above usually start an nvim-hs plugin host faster than the sandboxed Dyre setups I used, I also remoed Dyre as a dependency. A mechanism to reload changed configuration files doesn't exist yet. 

# TODO

- [x] New mechanism(s) to reload personal scripts, probably configurable and in a different Pull Request
- [x] Update documentation where necessary (README, Neovim and Neovim.Plugin mainly)

### CODE REVIEW

**Comment by tek** [comment]
do you actually use the reloading mechanism? It just seems rather exotic to implement this from the inside without sufficient demand.

**Comment by saep** [comment]
I don't like restarting my editor all the time. A working function to compile and restart a plugin host is probably enough, though.

`stack exec` takes 2-3 seconds on my laptop to start executing. `stack build --dry-run` takes 2-3 seconds as well. I want my editor to start fast. :-)

**Comment by tek** [comment]
fair enough! although it's only .3 seconds for the second time, which is still a number, I guess. but I want to point out that not restarting and having immediate startup are counterintuitive requirements ;)
In any case, this looks great!

**Comment by saep** [comment]
It's always 2-3 seconds for me. It might be my 6 year old laptop or something that has to do with the nix-integration.

Thank you for the review!

**Pull request merged**
