### PR TITLE
add Synchronous parameter to autocmd

### PR DESCRIPTION
**Pull request by tek**

### CODE REVIEW

**Comment by saep** [comment]
What is the difference in behavior between a synchronous and asynchronous autocmd? I always thought that the autocmds' behavior are asynchronous by default. If there is an issue with asynchronous autocmds, maybe it is better to just make synchronous autocmds the default?

The changes themselves look good, though. You should merge master or rebase them on the current master. 

> This branch has conflicts that must be resolved

**Comment by tek** [comment]
as far as I can tell, it only has an effect for my use case, `VimLeave`.
When defining an autocmd `async`, vim will call it using the `rpcnotify` function, meaning that the rpc runtime will not wait for a response. If this takes place during shutdown, the request will start processing in nvim-hs, but then get killed when the vim process terminates.
When using `rpcrequest`, vim will wait for the request to finish before quitting.

**Comment by tek** [comment]
another thing I could imagine is that errors might propagate with sync

**Comment by tek** [comment]
huh, it appears that my repo is broken and master couldn't be pulled :smile:

**Comment by tek** [comment]
fixed

**Comment by saep** [comment]
Do you mind writing a little changelog entry for version 2.1.0.0, which succinctly explains a migration path? (Add Async as the 2nd parameter to `addAutocmd`).

**Comment by saep** [comment]
Thanks!

**Pull request merged**
